#!/bin/sh
set -eu

# Universal LoRA training script - auto-detects platform and training backend
# - Apple Silicon Mac with MLX: GPU training (fast)
# - RPi5/Linux/Mac CPU: PyTorch CPU training (universal)

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
PROJECT_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/../../.." && pwd)
PYTHON=${PYTHON:-$PROJECT_ROOT/.venv/bin/python}

# Load .env if it exists
if [ -f "$PROJECT_ROOT/.env" ]; then
    set -a
    . "$PROJECT_ROOT/.env"
    set +a
fi

BASE_MODEL=${BASE_MODEL:-${OLLAMA_BASE_MODEL:-Qwen/Qwen2.5-1.5B-Instruct}}
MODEL_NAME=${OLLAMA_MODEL_NAME:-pip}
HF_TOKEN=${HF_TOKEN:-}

# Quantization level for `ollama create`, e.g. q4_K_M, q8_0, or empty to keep
# full precision. Shrinks both the on-disk store and the upload significantly
# (roughly 4x for q4 vs. unquantized) at some cost to output quality.
OLLAMA_QUANTIZE=${OLLAMA_QUANTIZE:-q4_K_M}

# Training intermediates (data split, LoRA adapter, fused HF model,
# Modelfile) - pure scratch space, fully regenerated by every run (you only
# ever train one model at a time), so it's wiped at the start of each one
# rather than accumulating stale files, and isn't namespaced per model name.
TRAINING_BUILD_DIR=${TRAINING_BUILD_DIR:-$SCRIPT_DIR/training/build}
ADAPTER_DIR=${ADAPTER_DIR:-$TRAINING_BUILD_DIR/adapters}
FUSED_DIR=${FUSED_DIR:-$TRAINING_BUILD_DIR/fused}
DATA_DIR=${DATA_DIR:-$TRAINING_BUILD_DIR/data}
TRAIN_ITERS=${TRAIN_ITERS:-300}
BATCH_SIZE=${BATCH_SIZE:-1}
LEARNING_RATE=${LEARNING_RATE:-1e-5}

# `ollama create` converts the fused HF model into Ollama's own
# content-addressed blob storage (blobs/ + manifests/, referenced by SHA256
# digest - not by filesystem path). That's fully portable, unlike the raw
# Modelfile (whose FROM line is an absolute, machine-specific path). Rather
# than relying on whatever OLLAMA_MODELS an already-running local `ollama
# serve` happens to use, spawn an isolated server scoped to this build with
# OLLAMA_MODELS pointed at $STORE_DIR, on a non-default port so it never
# collides with a real system Ollama instance. Unlike the training
# intermediates above, this is the final deliverable - it's not wiped, and
# is exactly what gets uploaded (see the final summary).
STORE_DIR=${STORE_DIR:-$SCRIPT_DIR/build/$MODEL_NAME}
OLLAMA_BUILD_HOST=${OLLAMA_BUILD_HOST:-127.0.0.1:11435}
OLLAMA_SERVE_PID=""

start_ollama_server() {
    mkdir -p "$STORE_DIR"
    OLLAMA_MODELS="$STORE_DIR" OLLAMA_HOST="$OLLAMA_BUILD_HOST" \
        ollama serve >"$TRAINING_BUILD_DIR/ollama-serve.log" 2>&1 &
    OLLAMA_SERVE_PID=$!

    deadline=$(( $(date +%s) + 30 ))
    while [ "$(date +%s)" -lt "$deadline" ]; do
        if ! kill -0 "$OLLAMA_SERVE_PID" 2>/dev/null; then
            echo "[train] ERROR: 'ollama serve' exited early. Check $TRAINING_BUILD_DIR/ollama-serve.log" >&2
            OLLAMA_SERVE_PID=""
            return 1
        fi
        if OLLAMA_HOST="$OLLAMA_BUILD_HOST" ollama list >/dev/null 2>&1; then
            return 0
        fi
        sleep 0.5
    done

    echo "[train] ERROR: Timed out waiting for isolated 'ollama serve' to start" >&2
    stop_ollama_server
    return 1
}

stop_ollama_server() {
    if [ -n "$OLLAMA_SERVE_PID" ]; then
        kill "$OLLAMA_SERVE_PID" 2>/dev/null || true
        wait "$OLLAMA_SERVE_PID" 2>/dev/null || true
        OLLAMA_SERVE_PID=""
    fi
}

trap stop_ollama_server EXIT

require_file() {
    if [ ! -e "$1" ]; then
        echo "[train] ERROR: missing $1" >&2
        exit 1
    fi
}

require_command() {
    if ! command -v "$1" >/dev/null 2>&1; then
        echo "[train] ERROR: '$1' is not installed or not on PATH" >&2
        exit 1
    fi
}

# Detect platform and training backend
detect_backend() {
    SYSTEM=$(uname -s)

    # Try to use GPU training on macOS if MLX is available
    if [ "$SYSTEM" = "Darwin" ]; then
        if "$PYTHON" -c "import mlx_lm" >/dev/null 2>&1; then
            echo "darwin"
            return 0
        fi
    fi

    # Default to CPU training (works everywhere)
    echo "aarch64"
}

BACKEND=$(detect_backend)

printf '%s\n' "[train] =========================================="
printf '%s\n' "[train] LoRA Personality Training"
printf '%s\n' "[train] =========================================="
printf '%s\n' "[train] Backend: $BACKEND"
printf '%s\n' "[train] Base model: $BASE_MODEL"
printf '%s\n' "[train]"

case "$BACKEND" in
    darwin)
        CHIP=$(sysctl -n machdep.cpu.brand_string 2>/dev/null | sed 's/.*Apple //' | awk '{print $1, $2}' || echo "Apple Silicon")
        printf '%s\n' "[train] Mode: GPU (MLX)"
        printf '%s\n' "[train] Hardware: $CHIP"
        ;;
    aarch64)
        CPUS=$(nproc 2>/dev/null || echo "?")
        printf '%s\n' "[train] Mode: CPU (PyTorch)"
        printf '%s\n' "[train] Architecture: ARM64 ($CPUS cores)"
        ;;
esac

printf '%s\n' "[train]"

require_file "$PYTHON"
require_file "$SCRIPT_DIR/training/personality.jsonl"
require_command "$PYTHON"

# Verify dependencies
case "$BACKEND" in
    darwin)
        if ! "$PYTHON" -c "import mlx_lm" >/dev/null 2>&1; then
            echo "[train] ERROR: MLX is not installed" >&2
            echo "[train] Install with: $PYTHON -m pip install mlx mlx-lm" >&2
            exit 1
        fi
        ;;
    aarch64)
        if ! "$PYTHON" -c "import torch; import peft; import transformers; import datasets" >/dev/null 2>&1; then
            echo "[train] ERROR: PyTorch/PEFT/Transformers/Datasets missing" >&2
            echo "[train] Install with: $PYTHON -m pip install torch peft transformers datasets" >&2
            exit 1
        fi
        ;;
esac

if ! command -v ollama >/dev/null 2>&1; then
    echo "[train] Warning: ollama not found - model creation will be skipped"
fi

printf '%s\n' "[train] Clearing training build directory: $TRAINING_BUILD_DIR"
rm -rf "$TRAINING_BUILD_DIR"
mkdir -p "$TRAINING_BUILD_DIR"

printf '%s\n' "[train] Preparing dataset"
mkdir -p "$DATA_DIR"

"$PYTHON" "$SCRIPT_DIR/training/prepare_data.py" \
    "$SCRIPT_DIR/training/personality.jsonl" \
    "$DATA_DIR"

require_file "$DATA_DIR/train.jsonl"
require_file "$DATA_DIR/valid.jsonl"

printf '%s\n' "[train] Training LoRA adapter"
mkdir -p "$ADAPTER_DIR"

HF_TOKEN="$HF_TOKEN" "$PYTHON" "$SCRIPT_DIR/training/$BACKEND/train_adapter.py" \
    "$BASE_MODEL" \
    "$DATA_DIR" \
    "$ADAPTER_DIR" \
    "$TRAIN_ITERS" \
    "$BATCH_SIZE" \
    "$LEARNING_RATE"

# MLX and PyTorch produce different files, so just check directory is not empty
if [ ! -d "$ADAPTER_DIR" ] || [ -z "$(ls -A $ADAPTER_DIR 2>/dev/null)" ]; then
    echo "[train] ERROR: Adapter directory is empty: $ADAPTER_DIR" >&2
    exit 1
fi

printf '%s\n' "[train] Merging adapter with base model"
mkdir -p "$FUSED_DIR"

HF_TOKEN="$HF_TOKEN" "$PYTHON" "$SCRIPT_DIR/training/$BACKEND/merge_adapter.py" \
    "$BASE_MODEL" \
    "$ADAPTER_DIR" \
    "$FUSED_DIR"

require_file "$FUSED_DIR/config.json"

printf '%s\n' "[train] Creating Ollama model"
MODELFILE="$TRAINING_BUILD_DIR/Modelfile"

sed "s|{{FUSED_MODEL_DIR}}|$FUSED_DIR|g" "$SCRIPT_DIR/training/Modelfile.template" > "$MODELFILE"

OLLAMA_STORE_READY=0
if command -v ollama >/dev/null 2>&1; then
    if start_ollama_server; then
        if [ -n "$OLLAMA_QUANTIZE" ]; then
            OLLAMA_HOST="$OLLAMA_BUILD_HOST" ollama create "$MODEL_NAME" -f "$MODELFILE" --quantize "$OLLAMA_QUANTIZE"
        else
            OLLAMA_HOST="$OLLAMA_BUILD_HOST" ollama create "$MODEL_NAME" -f "$MODELFILE"
        fi
        stop_ollama_server
        printf '%s\n' "[train] Created Ollama model: $MODEL_NAME"
        if [ -n "$OLLAMA_QUANTIZE" ]; then
            printf '%s\n' "[train] Quantization: $OLLAMA_QUANTIZE"
        fi

        # `ollama create` (especially with --quantize) leaves the
        # intermediate unquantized blob(s) behind in blobs/ - they're not
        # referenced by the final manifest, but nothing removes them
        # automatically, and they can be several GB each. Since this store is
        # scoped to a single build (not a shared cache), prune anything the
        # manifest doesn't reference before it gets uploaded.
        MANIFEST="$STORE_DIR/manifests/registry.ollama.ai/library/$MODEL_NAME/latest"
        "$PYTHON" - "$MANIFEST" "$STORE_DIR/blobs" <<'PYEOF'
import json, os, sys

manifest_path, blobs_dir = sys.argv[1], sys.argv[2]
with open(manifest_path) as f:
    manifest = json.load(f)

referenced = {manifest["config"]["digest"]}
referenced.update(layer["digest"] for layer in manifest["layers"])
referenced_filenames = {d.replace(":", "-") for d in referenced}

removed, freed = 0, 0
for name in os.listdir(blobs_dir):
    if name not in referenced_filenames:
        path = os.path.join(blobs_dir, name)
        freed += os.path.getsize(path)
        os.remove(path)
        removed += 1

if removed:
    print(f"[train] Pruned {removed} unreferenced blob(s), freed {freed / (1024**3):.2f} GB")
PYEOF

        printf '%s\n' "[train] Portable model store: $STORE_DIR"
        OLLAMA_STORE_READY=1
    else
        printf '%s\n' "[train] Could not start an isolated Ollama server - skipping model creation"
        printf '%s\n' "[train] To create manually: ollama create $MODEL_NAME -f $MODELFILE"
    fi
else
    printf '%s\n' "[train] Ollama not found - skipping model creation"
    printf '%s\n' "[train] To create manually: ollama create $MODEL_NAME -f $MODELFILE"
fi

printf '%s\n' "[train] ============================================"
printf '%s\n' "[train] Training complete!"
printf '%s\n' "[train] ============================================"
printf '%s\n' "[train]"
printf '%s\n' "[train] Model name:     $MODEL_NAME"
printf '%s\n' "[train] Merged model:   $FUSED_DIR"
printf '%s\n' "[train] Backend:        $BACKEND"
printf '%s\n' "[train]"
if [ "$OLLAMA_STORE_READY" = "1" ]; then
    printf '%s\n' "[train] Upload to RPi5:"
    printf '%s\n' "[train]   # 1. Upload the portable Ollama model store"
    printf '%s\n' "[train]   rsync -avz --progress $STORE_DIR/ pip@pip.local:/home/pip/robot/src/models/ollama/build/$MODEL_NAME/"
    printf '%s\n' "[train]"
    printf '%s\n' "[train]   # 2. Register it (verifies it, then merges into the robot's Ollama models dir - no ollama create/binary needed)"
    printf '%s\n' "[train]   ssh pip@pip.local '/home/pip/robot/src/models/ollama/install.sh $MODEL_NAME'"
    printf '%s\n' "[train]"
    printf '%s\n' "[train]   # 3. Restart robot service"
    printf '%s\n' "[train]   ssh pip@pip.local 'sudo systemctl restart robot.service'"
else
    printf '%s\n' "[train] Upload to RPi5 (manual - local Ollama unavailable, no portable store built):"
    printf '%s\n' "[train]   # 1. Upload the fused model (install.sh only registers a pre-built"
    printf '%s\n' "[train]   #    store, so without one you convert on-device instead)"
    printf '%s\n' "[train]   rsync -avz --progress $FUSED_DIR/ pip@pip.local:/home/pip/robot/src/models/ollama/training/build/fused/"
    printf '%s\n' "[train]"
    printf '%s\n' "[train]   # 2. Regenerate the Modelfile with a path valid on the RPi5, then"
    printf '%s\n' "[train]   #    run 'ollama create' there directly (requires ollama on the RPi5)"
    printf '%s\n' "[train]   ssh pip@pip.local 'cd /home/pip/robot/src/models/ollama && sed \"s|{{FUSED_MODEL_DIR}}|\$(pwd)/training/build/fused|g\" training/Modelfile.template > training/build/Modelfile && ollama create $MODEL_NAME -f training/build/Modelfile'"
    printf '%s\n' "[train]"
    printf '%s\n' "[train]   # 3. Restart robot service"
    printf '%s\n' "[train]   ssh pip@pip.local 'sudo systemctl restart robot.service'"
fi
printf '%s\n' "[train]"
printf '%s\n' "[train] Usage (local):"
printf '%s\n' "[train]   ollama run $MODEL_NAME \"Your prompt here\""
printf '%s\n' "[train]"
printf '%s\n' "[train] ============================================"
