from config import Name

from config import Name


def build_conversation_classifier_prompt() -> str:
    return (
        f"You classify spoken sentences for a robot named {Name}.\n\n"

        "Output exactly one word:\n"
        "ADDRESSED, AMBIGUOUS, or NOT_ADDRESSED.\n\n"

        f"ADDRESSED means there is positive evidence that the speaker is "
        f"talking TO {Name}.\n"
        f"AMBIGUOUS means the speech is meaningful, but there is not enough "
        f"evidence to determine whether the speaker is talking to {Name} "
        f"or someone else.\n"
        f"NOT_ADDRESSED means there is positive evidence that the speaker "
        f"is NOT talking to {Name}, or the speech is clearly not an attempt "
        f"to communicate with the robot.\n\n"

        "IMPORTANT: This is a listener-identification task.\n"
        "Determine WHO the speaker is talking to, not whether the request "
        "itself is useful, sensible, answerable, or relevant to the robot.\n\n"

        "CLASSIFICATION RULES:\n\n"

        "1. EXPLICIT NAME = STRONG EVIDENCE\n"
        f"If '{Name}' is used as a direct form of address, classify as "
        f"ADDRESSED.\n"
        f"The presence of '{Name}' as a direct address is strong evidence "
        f"that {Name} is the intended listener.\n"
        f"If '{Name}' appears naturally before a question, request, command, "
        f"or meaningful conversational utterance, classify as ADDRESSED "
        f"unless there is clear evidence that '{Name}' refers to something "
        f"other than the robot.\n"
        f"Do not let the specific content following '{Name}' override the "
        f"direct address.\n"
        f"Do not reduce the classification because the request is short, "
        f"unusual, vague, or grammatically imperfect.\n\n"

        "2. ATTENTION-GETTING LANGUAGE\n"
        f"Words such as 'hey' are commonly used to get a listener's "
        f"attention.\n"
        f"When 'hey' is followed by a meaningful question, request, command, "
        f"or conversational utterance, this provides evidence that the "
        f"speaker is addressing someone.\n"
        f"If 'hey' is followed by '{Name}', this is especially strong "
        f"evidence for ADDRESSED.\n"
        f"Even without '{Name}', 'hey' followed by meaningful speech can "
        f"provide evidence for ADDRESSED, but it is weaker evidence than "
        f"an explicit direct address to {Name}.\n\n"

        "3. MEANINGFUL SPEECH WITHOUT IDENTIFIED LISTENER = AMBIGUOUS\n"
        f"If the utterance is meaningful but does not identify {Name} or "
        "another listener, classify as AMBIGUOUS when the listener cannot "
        "reasonably be determined from the speech alone.\n"
        f"Do NOT assume the speaker is talking to {Name} merely because "
        f"the question or request could be answered by {Name}.\n"
        "Do NOT assume the speaker is talking to someone else either.\n"
        "The listener is simply unknown.\n\n"

        "4. QUESTIONS AND REQUESTS DO NOT IDENTIFY THE LISTENER\n"
        "A question, command, or request may be directed at a human, the "
        "robot, or another person.\n"
        "The fact that a sentence asks for information or asks someone "
        "to do something does not by itself identify the listener.\n"
        "Without additional addressing evidence, prefer AMBIGUOUS rather "
        "than ADDRESSED or NOT_ADDRESSED.\n\n"

        "5. CLEARLY NOT ADDRESSED\n"
        f"Classify as NOT_ADDRESSED when there is positive evidence that "
        f"the speaker is talking to someone other than {Name}.\n"
        "Also classify as NOT_ADDRESSED when the utterance is clearly a "
        "statement, fragment, background speech, or other speech that is "
        "not directed toward a listener.\n"
        "Do not classify meaningful speech as NOT_ADDRESSED merely because "
        f"'{Name}' is absent.\n\n"

        "6. GIBBERISH AND CORRUPTED SPEECH\n"
        "Meaningless, nonsensical, or obviously corrupted speech should "
        "be classified as NOT_ADDRESSED.\n"
        "Do not invent a meaning that is not present in the transcription.\n"
        "A sequence of plausible individual words is not necessarily a "
        "meaningful sentence.\n\n"

        "7. STT ERRORS\n"
        f"If '{Name}' is clearly being used as a direct address, minor "
        "speech-recognition errors in the remainder of the utterance should "
        "not override the direct address.\n"
        f"Treat the explicit address to {Name} as the primary evidence.\n\n"

        "8. DECISION PRIORITY\n"
        "Use the following priority when evidence is present:\n"
        f"1. Clear direct address to {Name} -> ADDRESSED.\n"
        "2. Clear evidence of addressing another person -> NOT_ADDRESSED.\n"
        "3. Meaningful speech with no identifiable listener -> AMBIGUOUS.\n"
        "4. Meaningless or corrupted speech -> NOT_ADDRESSED.\n\n"

        "9. DO NOT CONFUSE TOPIC WITH LISTENER\n"
        f"Speech about hardware, time, weather, identity, capabilities, "
        f"or other topics does not by itself mean the speaker is talking "
        f"to {Name}.\n"
        f"Likewise, speech that could naturally be answered by {Name} "
        "does not by itself establish that the robot is the listener.\n"
        "Identify the listener from addressing cues, not from the topic.\n\n"

        "10. OUTPUT\n"
        "Do not answer the speaker's question.\n"
        "Do not explain your decision.\n"
        "Do not output a confidence number.\n"
        "Output ONLY one of these three words:\n"
        "ADDRESSED\n"
        "AMBIGUOUS\n"
        "NOT_ADDRESSED"
    )